### PR TITLE
Option data-method needs to be set to the method id

### PR DESCRIPTION
**Pull request by rawcreative**

### CODE REVIEW

**Comment by ghost** [comment]
What's in `$data`?

---

Thank you for [this](https://github.com/ThemeFuse/Unyson-Mailer-Extension/pull/1/files#diff-e1267b5966364d31714aa3c358c8f445R51)

---

Making [`$data` a required attribute](https://github.com/ThemeFuse/Unyson-Mailer-Extension/pull/1/files#diff-37103b40d038920dbb5e8b957d21a0c8R3) will create fatal errors in scripts where it is already used without that attribute. I will make it optional `$data = array()`.

**Comment by rawcreative** [comment]
$data just contains the same values that's passed to the fw_render_view function in the contact form extension:

```
array(
     'form_values'       => $form_values,
     'shortcode_to_item' => $data['shortcode_to_item'],
)
```

**Comment by ghost** [comment]
I feel it's something wrong with that `$data`. Why the send method should know/care about some form values or shortcodes items? I think you should construct the finished email in your script/function and just tell the mailer to send it, but not mix extensions functionality.

Can you send me please your send method to `unyson[at]email.com` so I can take a look how you use the `form_values` and `shortcode_to_item`. Or if the send method it's not private, give me a link here.

**Comment by rawcreative** [comment]
The only reason that data is passed like that is because the form values are never passed to the send method, only the rendered email view: https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/extensions/contact-forms/class-fw-extension-contact-forms.php#L100-L103  If just the data was passed to the send method instead of the completed email then the individual send methods could do whatever they need with the data.. But right now, the contact-forms extension is managing that.

All my actual send method does is extract and parse the data, and sends it to an API as a json object. With the way it's currently set up, without that data parameter this isn't possible.

**Pull request merged**
